### ISSUE TITLE
NameError in `WmctrlExecutor::executable?`

### ISSUE THREAD

**Issue by pluiedev** [iberianpig/fusuma-plugin-wmctrl#13]
Ditto. It's trying to find `Fusuma::Plugin::Executors::WmctrlExecutor::Workspace`, whereas it should probably be `Fusuma::Plugin::Wmctrl::Workspace` — looks like there might be a preceding `Wmctrl::` missing, judging by the surrounding code, but I'm really not sure how Ruby namespace resolution works nowadays :sweat_smile: 

```
E, [2024-01-24T12:55:22.160877 #37410] ERROR -- : uninitialized constant Fusuma::Plugin::Executors::WmctrlExecutor::Workspace

        rescue Workspace::InvalidOption => e
               ^^^^^^^^^ (NameError)
```

**Comment by pluiedev** [comment]
Looked around and apparently this code is like, 3 years old and it referred to a top-level `Workspace` class here: https://github.com/iberianpig/fusuma-plugin-wmctrl/blob/fdd7d061b9966488ea687b339fb1f4ffeb19a56a/lib/fusuma/plugin/wmctrl/workspace.rb. Going to hot patch this out for now

**Comment by iberianpig** [comment]
@pluiedev thank you!
If you'd like, could you please create a pull request?
