### ISSUE TITLE
workspace: up/down

### ISSUE THREAD

**Issue by muellphi** [iberianpig/fusuma-plugin-wmctrl#5]
Hi,

do you think it is possible to implement a workspace: "up"/"down" direction for when using 2 rows of virtual desktops?

Thanks and all the best.

**Comment by iberianpig** [comment]
Yes, I think it is possible.
It needs to check col size and row size beforehand.

# Example

| row\col | col1 | col2 | col3 |
|:-------:|:----:|:----:|:----:|
| row1 | 0 | 1  | 2 |
| row2 | 3 | 4 | 5 |

* col_size = 3
* row_size = 2

If direction is,

* ` up`, it moves to the current_num - col size.
* `down`, it moves to the current_num + col size.
* `left`, it moves to the current_num - 1.
* `right`, it moves to the current_num + 1.


```ruby
current_num=`wmctrl -d | grep '*' | cut -d '*' -f 1`
#=> 1

current_num+down
#=> 4
```

**Comment by eugeneromero** [comment]
Would definitely love to see this implemented, as this is the fastest way of switching desktops with Fusuma by far. Any thoughts on when we might see this? Thanks in advance @iberianpig !

**Comment by iberianpig** [comment]
@muellphi @eugeneromero 
I've released `fusuma-plugin-wmctrl` gem.
Please update with `$ sudo gem update fusuma-plugin-wmctrl`.

**Comment by eugeneromero** [comment]
After updating the gem and the config as explained in #10, the plugin works as expected. Thank you very much for your work on this @iberianpig!
